let mapA = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['water', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'bridge', 'water'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let mapB = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['water', 'water', 'bridge', 'water', 'water', 'water', 'water', 'water', 'water', 'water'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass']]

let mapC = [['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let mapD = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'water', 'water', 'water', 'water', 'water', 'water', 'grass', 'grass', 'grass'],
['grass', 'water', 'water', 'water', 'water', 'water', 'water', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'horizontal_road'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let mapE = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass'],
['water', 'water', 'water', 'water', 'water', 'water', 'bridge', 'water', 'bridge', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let mapF = [['grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let mapG = [['grass', 'grass', 'water', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'water', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'water', 'grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'bridge', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let mapH = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass']]

let mapI = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass'],
['grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water', 'bridge', 'water', 'water', 'water', 'water', 'water', 'water', 'water', 'water'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['grass', 'vertical_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass']]

let mapJ = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['water', 'bridge', 'water', 'water', 'bridge', 'water', 'water', 'water', 'water', 'water'],
['grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass']]