

let elementL_right_up = [['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let elementL_left_up = [['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let elementL_left_down = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass']]

let elementL_right_down = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass']]

const elementI = [['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass']]

const element_line = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

const elementX = [['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'cross_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass']]

const test = [['grass', '1', 'grass', '1', 'grass', 'vertical_road', 'grass', '1', 'grass', '1', 'grass'],
['1', 'water', '1', 'grass', '1', 'vertical_road', '1', 'grass', '1', 'grass', '1'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['1', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'cross_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['1', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['1', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map1_A = [['water_vertical', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block'],
['bridge_2', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'vertical_road', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass'],
['water_vertical', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_left', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road'],
['water_vertical', 'grass', 'flowers', 'grass', 'grass', 'block', 'grass', 'grass', 'flowers', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map1_B = [['block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass'],
['flowers', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'flowers', 'grass', 'block', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'block', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'flowers', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map1_C = [['block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block'],
['grass', 'grass', 'grass', 'grass', 'window', 'window', 'window', 'grass', 'grass', 'grass', 'grass'],
['grass', 'flowers', 'grass', 'grass', 'window', 'window', 'window', 'grass', 'grass', 'block', 'grass'],
['grass', 'grass', 'grass', 'grass', 'window', 'door', 'window', 'grass', 'grass', 'grass', 'grass'],
['left_down', 'grass', 'grass', 'grass', 'grass', 'stairs', 'grass', 'grass', 'grass', 'grass', 'grass'],
['vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road'],
['bridge', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_3', 'grass', 'vertical_road', 'grass', 'grass'],
['right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'bridge_2', 'horizontal_road', 'left_up', 'grass', 'grass'],
['grass', 'block', 'grass', 'grass', 'flowers', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass']]

let map1_D = [['block', 'water_2', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4', 'block', 'block', 'block', 'block'],
['grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass'],
['grass', 'water_vertical', 'block', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass'],
['grass', 'water_vertical', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['right_up', 'bridge_2', 'left_down', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['vertical_road', 'water_vertical', 'vertical_road', 'grass', 't_right', 'horizontal_road', 'horizontal_road', 'horizontal_road', 't_left', 'grass', 'grass'],
['left_up', 'water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'water_vertical', 'right_down', 'horizontal_road', 'left_up', 'grass', 'block', 'grass', 'right_down', 'horizontal_road', 'horizontal_road'],
['grass', 'water_vertical', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map1_E = [['water_2', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4', 'block', 'block', 'block', 'block'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'left_down', 'grass', 'block'],
['water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'flowers', 'grass', 'right_up', 'horizontal_road', 'left_up', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'block', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'grass', 'grass', 'gflowers', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block']]

let map2_E = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'grass', 'block', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['water_3', 'grass', 'grass', 'grass', 'grass', 'block', 'flowers', 'grass', 'vertical_road', 'grass', 'block'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['water_vertical', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'block'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'block'],
['water_vertical', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'block'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'block'],
['bridge_2', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'block'],
['water_vertical', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'block'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'block']]

let map2_D = [['grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'water_1', 'water_3', 'grass', 'grass', 'grass', 'grass', 'grass', 'block', 'grass', 'grass'],
['grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'water_2', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal'],
['grass', 'grass', 'water_vertical', 'grass', 'grass', 'flowers', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'bridge_2', 'left_down', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water_vertical', 'right_down', 'horizontal_road', 'horizontal_road', 'bridge_2', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map2_C = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_1', 'water_3', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'bridge_2', 'left_down', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass'],
['grass', 'block', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'right_up'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'vertical_road'],
['grass', 'grass', 'grass', 'grass', 'flowers', 'grass', 'right_up', 'bridge_2', 'left_up', 'grass', 'vertical_road'],
['grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'water_vertical', 'grass', 'grass', 'vertical_road'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_down', 'bridge_2', 'left_down', 'grass', 'vertical_road'],
['water_2', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4', 'vertical_road', 'grass', 'vertical_road'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'left_up']]

let map2_B = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_3', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road'],
['water_vertical', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_1', 'bridge', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_3'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['grass', 'vertical_road', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'water_vertical'],
['grass', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'water_vertical'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'water_vertical'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical']]

let map2_A = [['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'right_up', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass', 'grass', 'water_2', 'water_horizontal'],
['water_vertical', 'vertical_road', 'grass', 'grass', 't_right', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'water_vertical', 'grass'],
['water_left', 'bridge', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_4', 'grass'],
['water_vertical', 'vertical_road', 'block', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'block', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'flowers', 'right_down', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]


let map3_A = [['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 't_up', 'left_down', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'right_up', 'horizontal_road', 't_left', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_left', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal'],
['water_vertical', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map3_B = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'water_1'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 't_right', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 't_right', 'horizontal_road', 'horizontal_road', 't_left', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_left', 'horizontal_road', 'left_up', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map3_C = [['water_vertical', 'water_2', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal'],
['water_vertical', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'water_vertical', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass'],
['water_4', 'water_vertical', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['horizontal_road', 'bridge_2', 'left_down', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_horizontal', 'water_4', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road'],
['flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass']]

let map3_D = [['water_horizontal', 'water_3', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_3', 'grass', 'grass', 'grass', 'grass'],
['grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'right_up', 'horizontal_road', 'left_down', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['flowers', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'water_vertical', 'grass', 'right_up', 'horizontal_road', 'horizontal_road'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'water_vertical', 'grass', 'vertical_road', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'left_up', 'grass', 'right_down', 'horizontal_road', 'bridge_2', 'horizontal_road', 'left_up', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass']]

let map3_E = [['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'block'],
['water_vertical', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 't_down', 'horizontal_road', 'left_down', 'grass', 'block'],
['water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'bridge', 'water_horizontal', 'water_horizontal'],
['grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'block'],
['flowers', 'grass', 'vertical_road', 'grass', 'right_up', 'horizontal_road', 'left_up', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['horizontal_road', 'horizontal_road', 't_left', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'block', 'grass', 'vertical_road', 'grass', 'block'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'block']]

let map4_E = [['grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 't_left', 'grass', 'water_2'],
['grass', 'vertical_road', 'grass', 'block', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'water_vertical'],
['water_3', 'vertical_road', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'water_vertical'],
['water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['water_vertical', 'vertical_road', 'grass', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'water_vertical'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'block', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['water_vertical', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'water_vertical'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'water_vertical'],
['bridge_2', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'water_vertical'],
['water_vertical', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['water_left', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4']]

let map4_D = [['grass', 'grass', 'grass', 'grass', 'grass', 'water_2', 'water_4', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'water_2', 'water_horizontal', 'water_horizontal', 'water_4', 'grass', 'right_up', 'left_down', 'grass', 'grass'],
['grass', 'grass', 'water_vertical', 'grass', 'flowers', 'grass', 'grass', 'vertical_road', 'vertical_road', 'water_2', 'water_horizontal'],
['grass', 'grass', 'water_vertical', 'grass', 'grass', 'right_up', 'horizontal_road', 'left_up', 'vertical_road', 'water_vertical', 'grass'],
['horizontal_road', 'horizontal_road', 'bridge_2', 'left_down', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'water_vertical', 'grass'],
['grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'water_vertical', 'grass'],
['grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'water_vertical', 'grass'],
['grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'vertical_road', 'flowers', 'grass', 'vertical_road', 'water_vertical', 'grass'],
['flowers', 'grass', 'water_vertical', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'right_down', 'bridge_2', 'horizontal_road'],
['grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass'],
['grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass']]

let map4_C = [['water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_3', 'grass', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'left_down', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'bridge_2', 'left_down', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'water_vertical', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'water_vertical', 'vertical_road', 'right_up', 'horizontal_road'],
['flowers', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'water_vertical', 'vertical_road', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'right_up', 'bridge_2', 'left_up', 'vertical_road', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'vertical_road', 'water_vertical', 'grass', 'vertical_road', 'grass'],
['grass', 'block', 'right_down', 'horizontal_road', 'left_up', 'grass', 'right_down', 'bridge_2', 'horizontal_road', 'left_up', 'grass'],
['water_2', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass']]

let map4_B = [['water_3', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'water_2'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['water_vertical', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 't_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'bridge_2'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'water_vertical'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'block', 'water_vertical'],
['water_1', 'bridge', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4'],
['grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'vertical_road', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass'],
['horizontal_road', 't_up', 'horizontal_road', 't_left', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass']]

let map4_A = [['water_left', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal'],
['water_vertical', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass'],
['water_left', 'bridge', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'bridge', 'water_horizontal', 'water_3', 'grass'],
['water_vertical', 't_right', 'horizontal_road', 'horizontal_road', 't_down', 'horizontal_road', 'horizontal_road', 't_left', 'grass', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'vertical_road', 'grass', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'flowers', 'right_down', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'block', 'flowers', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass'],
['water_vertical', 't_right', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'bridge', 'horizontal_road'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass']]

let map5_A = [['water_vertical', 't_right', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass'],
['water_vertical', 'vertical_road', 'grass', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'bridge_2', 'horizontal_road'],
['water_vertical', 'vertical_road', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'water_vertical', 'grass'],
['water_vertical', 'right_down', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'water_vertical', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'water_vertical', 'grass'],
['bridge_2', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'water_vertical', 'grass'],
['water_merge', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'water_merge', 'beach_down'],
['water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full']]

let map5_B = [['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['horizontal_road', 'horizontal_road', 'left_down', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'flowers', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'vertical_road', 'grass', 'vertical_road', 'grass', 'grass', 'flowers', 'vertical_road', 'grass', 'grass'],
['grass', 'grass', 'right_down', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road'],
['beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down'],
['water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full']]

let map5_C = [['water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'ruins_1', 'grass', 'grass', 'grass', 'ruins_2', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'right_up', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_down', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'ruins_2', 'vertical_road', 'grass', 'flowers', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'ruins_1', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'grass', 'ruins_1', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['water_vertical', 'flowers', 'grass', 'grass', 'vertical_road', 'grass', 'grass', 'grass', 'vertical_road', 'grass', 'grass'],
['bridge_2', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'left_up', 'grass', 'grass', 'grass', 'right_down', 'horizontal_road', 'horizontal_road'],
['water_merge', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down'],
['water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full']]

let map5_D = [['grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical', 'grass'],
['grass', 'grass', 'water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_4', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass'],
['grass', 'flowers', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'flowers', 'grass'],
['grass', 'ruins_1', 'wall_2', 'ruins_2', 'ruins_1', 'wall_2', 'ruins_2', 'grass', 'ruins_1', 'ruins_2', 'grass'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road'],
['beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down'],
['water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full']]

let map5_E = [['water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_3', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'ruins_1', 'wall_3', 'water_vertical', 'ruins_2', 'grass', 'grass', 'ruins_1', 'wall_3'],
['grass', 'flowers', 'grass', 'grass', 'grass', 'water_vertical', 'grass', 'grass', 'grass', 'grass', 'grass'],
['grass', 'grass', 'grass', 'grass', 'grass', 'water_1', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_horizontal', 'water_3'],
['wall_3', 'ruins_2', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'water_vertical'],
['grass', 'grass', 'grass', 'grass', 'wall', 'wall', 'wall', 'grass', 'wall', 'grass', 'water_vertical'],
['block', 'ruins_1', 'wall_3', 'wall_2', 'wall_2', 'temple', 'wall_2', 'ruins_1', 'wall_2', 'ruins_2', 'water_vertical'],
['horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'horizontal_road', 'water_vertical'],
['beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'beach_down', 'water_merge'],
['water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full', 'water_full']]

function element_map(map) {
    let divh = ''
    for (let i = 0; i < 11; i++) {
        let divw = ''
        for (let j = 0; j < 11; j++) {
            divw += "<div id ='" + map[i][j] + "' class = 'w'></div>"
        }
        divh += "<div>" + divw + "</div>"
    }
    document.getElementById('container').innerHTML = divh
}